### ISSUE TITLE
Nothing work

### ISSUE THREAD

**Issue by chronoss09** [nikolaevich23/make-pkg-bat#1]
I put the PS3_GAME folder inside the folder and when i launch make_pkg.bat, i have nothing :(, any solution ?

**Comment by nikolaevich23** [comment]
some logs will help. 
but try rename folder to title_id

**Comment by chronoss09** [comment]
It work thanks but on question, it can convert cfw backup to ofw to work with the new package manager for PS3 4xxxx ?
Sorry for my english :(

**Comment by nikolaevich23** [comment]
Yes, you can. Convert other tool: https://github.com/friendlyanon/CFW2OFW-Helper.
After that convert - pakage with my bat file.

**Comment by chronoss09** [comment]
But we need a HAN Enabler to play this game ?

**Comment by nikolaevich23** [comment]
Only install need HAN
