### ISSUE TITLE
No source-code and AV getting files as trojan

### ISSUE THREAD

**Issue by requeijaum** [nikolaevich23/make-pkg-bat#5]
Pretty strange to know that the developer deleted the source-code and only distributes binaries. I liked that BAT script, though.

Also: here is some scans from v3.1.1 to last update (today, v3.1.4):

https://www.virustotal.com/#/file/6791dd08739f413bc4a0b1ba4a6b0a8cdbf0892a47ba3904f7a1525662149255/detection

https://www.virustotal.com/#/file/bf1b16d1e663483f1813610ac281822d26d0934346982667a65ef926eb50b38e/detection

------------------------------------------

Please respond as this can be an issue if the files from the releases are really infected. I got a Sality trojan after using this tool and infected my USB drives.

**Comment by nikolaevich23** [comment]
Source exe: https://github.com/nikolaevich23/make-pkg-bat/blob/master/hiasm/MAKE_pkg.sha.
(This is just a gui shell, you can run from console like that: .\tools\make_pkg.bat 1 
.\tools\make_pkg.bat 2 and other)

Many anti-viruses are false positives after compressing the EXE file. Here's proof that there are no viruses.

https://www.virustotal.com/#/file/7c2d7bbe47fe3da5ab6751dc7ab4225974e5262bc995189f4cf644b75507e6e9/detection

after pack exe: https://www.virustotal.com/#/file/c1b1dc373dd48049f31857c4a057c5dd0a0d95d40c27c3418362c08188c7084d/detection (no Sality trojan). You infected exe file with trojan Sality trojan from somewhere else ...

Pack any exe file with upx.exe and the result will be the same ... 
Antiviruses are not all able to properly handle compressed exe files
upx.exe - not trijan too:
https://www.virustotal.com/#/file/0c3dc789d0a46493bd097526b920d913d930d96b1052cb331eec3ac560c89996/detection

**Comment by requeijaum** [comment]
Thanks for the reply, @nikolaevich23 !
I confirm that I got infected somewhere else.
The UPX.exe got some false positives after all. ;)
